schema:
  - https://graphql.datocms.com/:
      headers:
        Authorization: Bearer 8d5106178bc5d178a9a05ae39e933e
extensions:
  endpoints:
    default:
      url: https://graphql.datocms.com/
      headers:
        Authorization: Bearer 8d5106178bc5d178a9a05ae39e933e
